SELECT j.id AS id, 
       j.name AS name, 
       j.media_id AS media_id, 
       j.job_category_id AS job_category_id, 
       j.job_type_id AS job_type_id, 
       j.description AS description, 
       j.detail AS detail, 
       j.business_skill AS business_skill, 
       j.knowledge AS knowledge, 
       j.location AS location, 
       j.activity AS activity, 
       j.academic_degree_doctor AS academic_degree_doctor, 
       j.academic_degree_master AS academic_degree_master, 
       j.academic_degree_professional AS academic_degree_professional, 
       j.academic_degree_bachelor AS academic_degree_bachelor, 
       j.salary_statistic_group AS salary_statistic_group, 
       j.salary_range_first_year AS salary_range_first_year, 
       j.salary_range_average AS salary_range_average, 
       j.salary_range_remarks AS salary_range_remarks, 
       j.restriction AS restriction, 
       j.estimated_total_workers AS estimated_total_workers, 
       j.remarks AS remarks, 
       j.url AS url, 
       j.seo_description AS seo_description, 
       j.seo_keywords AS seo_keywords, 
       j.sort_order AS sort_order, 
       j.publish_status AS publish_status, 
       j.version AS version, 
       j.created_by AS created_by, 
       j.created AS created, 
       j.modified AS modified, 
       j.deleted AS deleted, 
       jc.id AS job_category_id, 
       jc.name AS job_category_name, 
       jc.sort_order AS job_category_sort_order, 
       jc.created_by AS job_category_created_by, 
       jc.created AS job_category_created, 
       jc.modified AS job_category_modified, 
       jc.deleted AS job_category_deleted, 
       jt.id AS job_type_id, 
       jt.name AS job_type_name, 
       jt.job_category_id AS job_type_category_id, 
       jt.sort_order AS job_type_sort_order, 
       jt.created_by AS job_type_created_by, 
       jt.created AS job_type_created, 
       jt.modified AS job_type_modified, 
       jt.deleted AS job_type_deleted 
FROM jobs j 
INNER JOIN job_categories jc ON jc.id = j.job_category_id 
INNER JOIN job_types jt ON jt.id = j.job_type_id 
WHERE MATCH (j.name, j.description, j.detail, j.business_skill, j.knowledge, j.location, j.activity, j.salary_range_remarks, j.restriction, j.remarks) AGAINST ('キャビンアテンダント' IN BOOLEAN MODE) 
AND j.deleted = 0 
AND jc.deleted = 0 
AND jt.deleted = 0;
